refresh_rate: 30 seconds
appenders:
    stdout:
        kind: console
    admin_log:
        kind: file
        path: "resources/log/admin.log"
        encoder:
            pattern: "{d} - {m}{n}"
root:
    level: info
    appenders:
        - admin_log
loggers:
    app::stdout:
        level: info
        appenders:
            - stdout
        additive: false
