[package]
name = "Gateman"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }